import { GraphNode, GraphEdge, AgentTrack } from '../types';

export const mockGraphNodes: GraphNode[] = [
  // --- CASTLE SOVEREIGNTY ZONE (LOCAL WORKSTATION) ---
  {
    id: 'agt-builder',
    type: 'agent',
    name: 'Tectonic-Builder',
    label: 'Engine Builder & Test Runner',
    category: 'castle',
    x: 340,
    y: 220,
    status: 'executing',
    iconType: 'terminal',
    metadata: {
      model: 'llama3.2:latest',
      charter: 'Compile, test, and enforce zero-regression cargo test passes.',
      capabilities: ['shell:cargo', 'fs:read_write', 'mcp:github'],
    },
  },
  {
    id: 'agt-doc',
    type: 'agent',
    name: 'Doc-Synthesizer',
    label: 'Spec & Documentation Agent',
    category: 'castle',
    x: 340,
    y: 380,
    status: 'active',
    iconType: 'file-text',
    metadata: {
      model: 'llama3.2:latest',
      charter: 'Synchronize engine architectures with Hugo docs & Google Workspace.',
      capabilities: ['fs:read', 'mcp:google_workspace', 'mcp:github'],
    },
  },
  {
    id: 'agt-sentinel',
    type: 'agent',
    name: 'Castle-Sentinel',
    label: 'Local Perimeter Guard',
    category: 'castle',
    x: 180,
    y: 300,
    status: 'idle',
    iconType: 'shield',
    metadata: {
      model: 'qwen2.5-coder:7b',
      charter: "Private castle daemon guarding Alice's machine. Zero untrusted remote exec.",
      capabilities: ['audit:events', 'castle:gate'],
    },
  },
  {
    id: 'agt-scratch',
    type: 'agent',
    name: 'Scratch-Worker',
    label: 'Ephemeral Task Worker',
    category: 'castle',
    x: 180,
    y: 450,
    status: 'idle',
    iconType: 'cpu',
    metadata: {
      model: 'llama3.2:3b',
      charter: 'Quick one-off data parsing and log formatting sandbox.',
      capabilities: ['fs:read'],
    },
  },
  // Castle Local Tools
  {
    id: 'tool-cargo',
    type: 'tool',
    name: 'shell:cargo',
    label: 'Cargo Build & Test Runner',
    category: 'castle',
    x: 480,
    y: 170,
    status: 'active',
    iconType: 'terminal',
    metadata: {
      details: 'Subprocess execution in isolated workspace sandbox',
    },
  },
  {
    id: 'tool-fs',
    type: 'tool',
    name: 'fs:read_write',
    label: 'Local Filesystem Host',
    category: 'castle',
    x: 480,
    y: 300,
    status: 'idle',
    iconType: 'hard-drive',
    metadata: {
      details: 'Restricted to local repo workspace directory',
    },
  },
  {
    id: 'tool-git',
    type: 'tool',
    name: 'git:cli',
    label: 'Git Subsystem',
    category: 'castle',
    x: 480,
    y: 430,
    status: 'idle',
    iconType: 'git-branch',
    metadata: {
      details: 'Inspect commits, generate unified diffs, branch management',
    },
  },
  // Castle Local Services
  {
    id: 'storage-db',
    type: 'storage',
    name: 'tetonic.db (SQLite)',
    label: 'Encrypted Event Ledger',
    category: 'castle',
    x: 180,
    y: 170,
    status: 'active',
    iconType: 'database',
    metadata: {
      details: 'HMAC verified tamper-evident local audit log',
    },
  },
  {
    id: 'inf-ollama',
    type: 'inference',
    name: 'Ollama Loopback',
    label: 'Hardware Inference (38ms)',
    category: 'castle',
    x: 340,
    y: 530,
    status: 'active',
    iconType: 'cpu',
    metadata: {
      endpoint: 'http://127.0.0.1:11434',
      model: 'llama3.2:latest',
      latencyMs: 38,
    },
  },

  // --- TEAM GUILD ZONE (SHARED COLLABORATION) ---
  {
    id: 'usr-susan',
    type: 'human',
    name: 'Susan Vance',
    label: 'Team Lead (@susan_lead)',
    category: 'team',
    x: 740,
    y: 200,
    status: 'active',
    iconType: 'user',
    metadata: {
      details: 'Platform Core Guild Lead. Workstation: Desktop (Remote).',
    },
  },
  {
    id: 'agt-remote-guard',
    type: 'agent',
    name: 'LintSentinel',
    label: 'Static Analysis Sentinel',
    category: 'team',
    x: 740,
    y: 360,
    status: 'active',
    iconType: 'bot',
    metadata: {
      model: 'deepseek-coder:6.7b',
      charter: 'Susan-owned agent pledged to Platform Guild. AST hygiene.',
      capabilities: ['lint:cargo-clippy', 'mcp:jira'],
    },
  },

  // --- EXTERNAL CONNECTORS & OUTPOSTS ---
  {
    id: 'mcp-github',
    type: 'connector',
    name: 'GitHub MCP Connector',
    label: 'tetonic-labs/tetonic',
    category: 'external',
    x: 1040,
    y: 200,
    status: 'active',
    iconType: 'github',
    metadata: {
      connectorType: 'github',
      details: 'PR reviews, issues, workflow dispatch via MCP protocol',
    },
  },
  {
    id: 'mcp-jira',
    type: 'connector',
    name: 'Jira Service Desk MCP',
    label: 'TET-Platform Project',
    category: 'external',
    x: 1040,
    y: 360,
    status: 'idle',
    iconType: 'trello',
    metadata: {
      connectorType: 'jira',
      details: 'Sync sprint epics and automated regression tickets',
    },
  },
  {
    id: 'mcp-google',
    type: 'connector',
    name: 'Google Workspace MCP',
    label: 'Engineering Architecture Docs',
    category: 'external',
    x: 1040,
    y: 520,
    status: 'active',
    iconType: 'globe',
    metadata: {
      connectorType: 'google',
      details: 'ADR documentation sync and team shared drive storage',
    },
  },
];

export const mockGraphEdges: GraphEdge[] = [
  // Tectonic-Builder using shell:cargo (Active execution beam)
  {
    id: 'edge-builder-cargo',
    source: 'agt-builder',
    target: 'tool-cargo',
    type: 'tool_usage',
    label: 'cargo test -p tetonic-core',
    isActive: true,
    activityLabel: 'Executing 46 unit tests',
    pulseColor: '#D08A4C',
  },
  // Tectonic-Builder querying GitHub MCP Connector
  {
    id: 'edge-builder-github',
    source: 'agt-builder',
    target: 'mcp-github',
    type: 'mcp_query',
    label: 'Fetch PR #142 diff',
    isActive: true,
    activityLabel: 'Streaming pull request patch',
    pulseColor: '#8B5E3F',
  },
  // Inter-agent communication: Builder -> Doc-Synthesizer
  {
    id: 'edge-builder-doc',
    source: 'agt-builder',
    target: 'agt-doc',
    type: 'agent_comm',
    label: 'Handoff: Architecture Spec',
    isActive: true,
    activityLabel: 'Notified doc update required',
    pulseColor: '#10B981',
  },
  // Doc-Synthesizer pushing to Google Workspace MCP
  {
    id: 'edge-doc-google',
    source: 'agt-doc',
    target: 'mcp-google',
    type: 'mcp_query',
    label: 'Sync ADR-009',
    isActive: true,
    activityLabel: 'Writing ADR markdown to Drive',
    pulseColor: '#3B82F6',
  },
  // Sentinel guarding local storage db
  {
    id: 'edge-sentinel-db',
    source: 'agt-sentinel',
    target: 'storage-db',
    type: 'castle_gate',
    label: 'HMAC Event Verify',
    isActive: false,
  },
  // Builder using local Ollama Loopback
  {
    id: 'edge-builder-ollama',
    source: 'agt-builder',
    target: 'inf-ollama',
    type: 'tool_usage',
    label: 'Context tokens (38ms)',
    isActive: true,
    pulseColor: '#D08A4C',
  },
  // LintSentinel reporting to Susan
  {
    id: 'edge-sentinel-susan',
    source: 'agt-remote-guard',
    target: 'usr-susan',
    type: 'agent_comm',
    label: 'AST Health Report',
    isActive: false,
  },
  // LintSentinel connecting to Jira
  {
    id: 'edge-sentinel-jira',
    source: 'agt-remote-guard',
    target: 'mcp-jira',
    type: 'mcp_query',
    label: 'Query TET-402',
    isActive: false,
  },
];

export const mockAgentTracks: Record<string, AgentTrack> = {
  'agt-builder': {
    agentId: 'agt-builder',
    agentName: 'Tectonic-Builder',
    currentStatus: 'executing',
    totalTokens: 384102,
    steps: [
      {
        id: 'st-1',
        stepNumber: 1,
        timestamp: '19:40:12',
        type: 'directive',
        title: 'Received Human Directive',
        inputPayload:
          'Verify that splitting agent tests into agent_tests.rs preserved 100% test pass rates.',
        status: 'success',
      },
      {
        id: 'st-2',
        stepNumber: 2,
        timestamp: '19:40:15',
        type: 'thought',
        title: 'Formulated Multi-Step Validation Strategy',
        inputPayload:
          'Monolithic agent.rs was pruned by 1,638 lines. I will query the GitHub repository for recent commit changes, invoke shell:cargo in the local sandbox, and delegate documentation synchronization to Doc-Synthesizer.',
        tokens: 64,
        status: 'success',
      },
      {
        id: 'st-3',
        stepNumber: 3,
        timestamp: '19:40:22',
        type: 'mcp_query',
        title: 'Queried GitHub MCP Connector',
        targetNodeId: 'mcp-github',
        targetNodeName: 'GitHub MCP Connector',
        inputPayload: 'github.get_commit_diff({ repo: "tetonic-labs/tetonic", commit: "HEAD" })',
        outputPayload:
          'Found modified file core/tetonic-core/src/agent.rs and new untracked file core/tetonic-core/src/agent_tests.rs (+1637 lines).',
        durationMs: 420,
        status: 'success',
      },
      {
        id: 'st-4',
        stepNumber: 4,
        timestamp: '19:40:28',
        type: 'gate_approval',
        title: 'Requested Gatekeeper Authorization',
        inputPayload: 'cargo test -p tetonic-core -- --nocapture',
        outputPayload: 'Human gatekeeper Alice granted signed authorization token.',
        durationMs: 12000,
        status: 'success',
      },
      {
        id: 'st-5',
        stepNumber: 5,
        timestamp: '19:40:41',
        type: 'tool_execution',
        title: 'Executed shell:cargo in Local Sandbox',
        targetNodeId: 'tool-cargo',
        targetNodeName: 'shell:cargo',
        inputPayload: 'cargo test -p tetonic-core -- --nocapture',
        outputPayload:
          'running 46 tests\ntest agent_tests::test_agent_instantiation ... ok\n[... 45 more tests ...]\ntest result: ok. 46 passed; 0 failed',
        durationMs: 7120,
        status: 'success',
      },
      {
        id: 'st-6',
        stepNumber: 6,
        timestamp: '19:41:00',
        type: 'peer_comm',
        title: 'Dispatched Handoff to Doc-Synthesizer',
        targetNodeId: 'agt-doc',
        targetNodeName: 'Doc-Synthesizer',
        inputPayload:
          'Agent core refactoring verified: 46/46 passed. Please update the architectural specification and sync with Google Workspace.',
        status: 'running',
      },
    ],
  },

  'agt-doc': {
    agentId: 'agt-doc',
    agentName: 'Doc-Synthesizer',
    currentStatus: 'active',
    totalTokens: 89400,
    steps: [
      {
        id: 'st-d1',
        stepNumber: 1,
        timestamp: '19:41:02',
        type: 'peer_comm',
        title: 'Received Handoff from Tectonic-Builder',
        inputPayload: 'Agent core refactoring verified: 46/46 passed. Update architectural spec.',
        status: 'success',
      },
      {
        id: 'st-d2',
        stepNumber: 2,
        timestamp: '19:41:08',
        type: 'thought',
        title: 'Synthesizing Architecture Specification',
        inputPayload:
          'Formulating updated ADR markdown documentation detailing the de-monolithing of agent.rs and verification via tetonic-arch-gate.',
        tokens: 42,
        status: 'success',
      },
      {
        id: 'st-d3',
        stepNumber: 3,
        timestamp: '19:41:15',
        type: 'mcp_query',
        title: 'Syncing to Google Workspace MCP',
        targetNodeId: 'mcp-google',
        targetNodeName: 'Google Workspace MCP',
        inputPayload:
          'google_docs.update_document({ docId: "ADR-009-core-architecture", content: "[ADR-009 Document]" })',
        outputPayload: 'Document updated successfully at 19:41:16. Version 4.2 synced.',
        durationMs: 890,
        status: 'running',
      },
    ],
  },

  'agt-sentinel': {
    agentId: 'agt-sentinel',
    agentName: 'Castle-Sentinel',
    currentStatus: 'idle',
    totalTokens: 142050,
    steps: [
      {
        id: 'st-s1',
        stepNumber: 1,
        timestamp: '19:38:00',
        type: 'thought',
        title: 'Castle Perimeter Health Scan',
        inputPayload:
          'Inspecting network socket bindings. Loopback binding on 127.0.0.1:11434 verified. Zero external ingress listening.',
        tokens: 38,
        status: 'success',
      },
      {
        id: 'st-s2',
        stepNumber: 2,
        timestamp: '19:38:05',
        type: 'tool_execution',
        title: 'Audited SQLite tetonic.db Ledger',
        targetNodeId: 'storage-db',
        targetNodeName: 'tetonic.db (SQLite)',
        inputPayload: 'SELECT COUNT(*) FROM audit_events WHERE verified = 1;',
        outputPayload: '1,429 tamper-evident records verified.',
        durationMs: 45,
        status: 'success',
      },
    ],
  },
};
