#!/usr/bin/env python3
"""Generate fabric protocol documentation from Rust sources (M5-1).

Usage:
    python scripts/gen_fabric_protocol_doc.py
    python scripts/gen_fabric_protocol_doc.py --check
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROTO = ROOT / "atmos" / "lokai-fabric-protocol" / "src"
OUT = ROOT.parent / "docs" / "implementation" / "contracts" / "fabric-protocol-v1.md"


def extract_rust_enum(path: Path, enum_name: str) -> list[str]:
    text = path.read_text(encoding="utf-8")
    m = re.search(rf"pub enum {enum_name}\s*\{{([^}}]+)\}}", text, re.S)
    if not m:
        return []
    return [line.strip().rstrip(",") for line in m.group(1).splitlines() if line.strip()]


def extract_struct_fields(path: Path, struct_name: str) -> list[str]:
    text = path.read_text(encoding="utf-8")
    m = re.search(rf"pub struct {struct_name}\b(?:<[^>]+>)?\s*\{{([^}}]+)\}}", text, re.S)
    if not m:
        return []
    fields = []
    for line in m.group(1).splitlines():
        line = line.strip()
        if not line or line.startswith("//"):
            continue
        name = line.split(":")[0].strip().removeprefix("pub ")
        fields.append(name)
    return fields


def render() -> str:
    error_codes = extract_rust_enum(PROTO / "error.rs", "FabricErrorCode")
    job_kinds = extract_rust_enum(PROTO / "job.rs", "JobKind")
    envelope_fields = extract_struct_fields(PROTO / "envelope.rs", "FabricEnvelope")
    job_fields = extract_struct_fields(PROTO / "job.rs", "JobEnvelope")
    artifact_fields = extract_struct_fields(PROTO / "job.rs", "ArtifactReference")
    deadline_fields = extract_struct_fields(PROTO / "job.rs", "JobDeadlines")
    capability_fields = extract_struct_fields(
        PROTO / "capability_document.rs", "WorkerCapabilities"
    )

    lines = [
        "# Fabric Protocol v1 (generated)",
        "",
        "> Auto-generated by `engine/scripts/gen_fabric_protocol_doc.py`. Do not edit by hand.",
        "",
        "Transport-neutral coordinator↔worker contract in `lokai-fabric-protocol`.",
        "Coordinator-side transport, retries, and legacy adaptation in `lokai-fabric-client`.",
        "",
        "## Protocol envelope",
        "",
        "`FabricEnvelope<T>` fields:",
        "",
    ]
    for f in envelope_fields:
        lines.append(f"- `{f}`")
    lines.extend(["", "## Job envelope", "", "`JobEnvelope` fields:", ""])
    for f in job_fields:
        lines.append(f"- `{f}`")
    lines.extend(
        [
            "",
            "### Digest-bound input artifacts (M5-3)",
            "",
            "`ArtifactReference` fields:",
            "",
        ]
    )
    for f in artifact_fields:
        lines.append(f"- `{f}`")
    lines.extend(
        [
            "",
            "Every artifact reference must carry a non-empty immutable digest. Typed-job",
            "placement preserves these references and revalidates worker trust, capability",
            "freshness, job-kind/model support, limits, policy epoch, workspace state,",
            "coordinator artifact-store digests, and sandbox requirements immediately before",
            "remote dispatch.",
        ]
    )
    lines.extend(["", "## Job deadlines", "", "`JobDeadlines` fields:", ""])
    for f in deadline_fields:
        lines.append(f"- `{f}`")
    lines.extend(["", "## Job kinds", ""])
    for k in job_kinds:
        lines.append(f"- `{k}`")
    lines.extend(["", "## Worker capabilities (M5-2)", "", "`WorkerCapabilities` fields:", ""])
    for f in capability_fields:
        lines.append(f"- `{f}`")
    lines.extend(["", "## Error codes", ""])
    for c in error_codes:
        lines.append(f"- `{c}`")
    result_body_fields = extract_struct_fields(PROTO / "result.rs", "SignedResultBody")
    lines.extend(
        [
            "",
            "## Signed result envelope (M5-4)",
            "",
            "`SignedResultBody` fields (canonical JSON is signed; signature is provenance-only):",
            "",
        ]
    )
    for f in result_body_fields:
        lines.append(f"- `{f}`")
    lines.extend(
        [
            "",
            "`ResultEnvelope` adds `signature` and untrusted `payload`.",
            "Coordinator validates channel identity, signing-key registry, lease/task binding,",
            "digests, and sizes before quarantine; RunSupervisor alone accepts task winners.",
            "",
            "## Lifecycle messages",
            "",
            "JobOffer, JobAccepted, JobRejected, JobStarted, Heartbeat, LeaseRenewal*,",
            "ProgressUpdate, Cancellation*, JobCompleted, JobFailed, ResultRejected,",
            "WorkerDraining, WorkerUnavailable, ResultEnvelope",
            "",
            "## Worker ingress",
            "",
            "`IngressState` deduplicates by attempt+lease+epoch+idempotency_key;",
            "persists on worker in `fabric_ingress_records` (lokai-node).",
            "",
            "## Legacy adapter",
            "",
            "`lokai-fabric-client` translates `JobEnvelope` → `/v1/chat` JSON;",
            "legacy workers advertise `legacy_v1_chat_only` via `/v1/capabilities`.",
            "Remote Ok results must carry a signed `ResultEnvelope` (M5-4).",
            "",
            "## Verification",
            "",
            "- `cargo test -p lokai-fabric-protocol`",
            "- `cargo test -p lokai-fabric-client`",
            "- `cargo test -p lokai-node`",
            "- Architecture gate: `check_fabric_protocol_isolation`",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUT.exists():
            sys.stderr.write(f"missing: {OUT}\n")
            return 1
        if OUT.read_text(encoding="utf-8") != content:
            sys.stderr.write(f"stale: {OUT}; run gen_fabric_protocol_doc.py\n")
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
