[package]
name = "tetonic-bench"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
lokai-index = { path = "../../strata/lokai-index" }
lokai-tools = { path = "../../litho/lokai-tools" }
lokai-core = { package = "tetonic-core", path = "../../core/tetonic-core" }
serde_json = { workspace = true }
anyhow = { workspace = true }
