[package]
name = "lokai-core"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
lokai-inference = { path = "../../atmos/lokai-inference" }
lokai-policy = { path = "../../core/lokai-policy" }
lokai-telemetry = { path = "../../core/lokai-telemetry" }
lokai-domain = { path = "../../core/lokai-domain" }
serde_json = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
futures-util = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }
tokenizers = { workspace = true }
tokio = { workspace = true, features = ["rt"] }

[dev-dependencies]
lokai-tools = { path = "../../litho/lokai-tools" }
lokai-transaction = { path = "../../core/lokai-transaction" }
tempfile = "3"
tokio = { workspace = true, features = ["rt", "macros"] }
chrono.workspace = true
