//! Universal perception types for continuous (live-world) agent operation.
//!
//! A [`Perception`] is what a [`WorldAdapter`] delivers to an agent's brain
//! each tick. The adapter does the preprocessing — computing signals, tagging
//! urgency, packaging events — so the brain receives already-meaningful data
//! rather than raw world bytes.
//!
//! # Two execution models
//!
//! | Interface        | Entry point           | World tempo         |
//! |------------------|-----------------------|---------------------|
//! | [`BrainRequest`] | `Brain::complete()`   | paused (turn-based) |
//! | [`Perception`]   | `Brain::perceive()`   | live (continuous)   |
//!
//! Both are supported by the same [`Brain`] trait. Swap the world adapter and
//! the same agent works in a game world, a robotic arm, a CI pipeline, or a
//! chat session.
//!
//! [`Brain`]: crate::Brain
//! [`BrainRequest`]: crate::BrainRequest
//! [`WorldAdapter`]: crate::WorldAdapter

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use thiserror::Error;

use crate::BrainPathway;

// ── Perception ────────────────────────────────────────────────────────────────

/// Pre-processed sensory data delivered to an agent's brain each tick.
///
/// The world adapter computes this from raw environment state — analogous to
/// peripheral-nervous-system preprocessing in biological systems. By the time
/// the brain sees a `Perception`, it carries three distinct views of the world:
///
/// - **signals** — pre-computed named metrics with change flags (System 1 fuel)
/// - **events**  — discrete occurrences that need attention (routing hooks)
/// - **state**   — the full world snapshot (System 2 fuel, opaque to the brain)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Perception {
    /// When this perception was generated by the adapter.
    pub when: DateTime<Utc>,
    /// Monotonic counter — for ordering and detecting dropped ticks.
    pub sequence: u64,
    /// Adapter's overall urgency assessment for this tick.
    pub urgency: Urgency,
    /// Pre-computed named metrics. System 1 pattern-matches against these;
    /// no model call needed for signal-only routing.
    pub signals: Vec<Signal>,
    /// Discrete occurrences since the last tick. Carry rich content for System 2.
    pub events: Vec<WorldEvent>,
    /// Full world snapshot — passed to System 2 as context.
    /// Opaque to the brain infrastructure; the model interprets it via its
    /// system prompt which describes the world's schema.
    pub state: WorldState,
}

// ── Urgency ───────────────────────────────────────────────────────────────────

/// Adapter-assigned urgency level for a perception or signal.
///
/// Used by `DualProcessBrain` to decide whether to engage System 2 immediately
/// or let System 1 handle the tick alone.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum Urgency {
    /// Normal background state — no notable changes.
    #[default]
    Background,
    /// Something changed but no immediate action required.
    Low,
    /// Attention warranted; System 1 should respond.
    Medium,
    /// Prompt action required; consider escalating to System 2.
    High,
    /// Immediate response mandatory; always escalate to System 2.
    Critical,
}

// ── Signal ────────────────────────────────────────────────────────────────────

/// A named, typed, pre-computed metric the adapter extracts from raw world state.
///
/// The adapter decides which signals matter for its world. A village adapter
/// might emit `grain_level: 0.23 (falling)`. A robotic adapter might emit
/// `joint_angle: 42.1 (rising)`. A CI adapter might emit `test_failures: 3 (changed)`.
///
/// The signal *name* and *schema* are world-specific; the *structure* is universal.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    /// World-defined name (e.g. `"grain_level"`, `"visitor_count"`).
    pub name: String,
    pub value: SignalValue,
    /// True when this value changed from the previous tick.
    pub changed: bool,
    /// Optional trend direction, adapter-computed.
    pub trend: Option<Trend>,
    /// Per-signal urgency — may differ from the overall perception urgency.
    pub urgency: Urgency,
}

impl Signal {
    pub fn as_bool(&self) -> Option<bool> {
        match &self.value {
            SignalValue::Bool(b) => Some(*b),
            _ => None,
        }
    }

    pub fn as_float(&self) -> Option<f64> {
        match &self.value {
            SignalValue::Float(f) => Some(*f),
            SignalValue::Int(i) => Some(*i as f64),
            _ => None,
        }
    }

    pub fn as_int(&self) -> Option<i64> {
        match &self.value {
            SignalValue::Int(i) => Some(*i),
            _ => None,
        }
    }
}

/// The typed value of a [`Signal`].
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SignalValue {
    Bool(bool),
    Int(i64),
    Float(f64),
    Text(String),
}

/// Direction a signal is moving over time.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Trend {
    Rising,
    Falling,
    Stable,
}

// ── WorldEvent ────────────────────────────────────────────────────────────────

/// A discrete occurrence in the world since the last tick.
///
/// Unlike signals (which represent ongoing state), events represent *things that
/// happened*: a message arrived, a resource was exhausted, a visitor petitioned.
/// System 1 routes on `kind`; System 2 reads the full `payload`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorldEvent {
    /// World-defined event kind (e.g. `"agent_message"`, `"resource_depleted"`).
    pub kind: String,
    /// Who or what produced this event (agent id, system component, external input).
    pub source: Option<String>,
    /// Full event-specific content. Schema is world-defined.
    #[serde(default)]
    pub payload: Value,
    /// How urgently this event needs a response.
    pub urgency: Urgency,
}

// ── WorldState ────────────────────────────────────────────────────────────────

/// The full world snapshot at the time of this perception tick.
///
/// Opaque to the brain runtime — the model interprets it using the world
/// schema description embedded in the agent's system prompt. This is System 2's
/// primary information source; System 1 works from `signals` and event `kind`s.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorldState {
    /// Identifies the world/environment type.
    /// Agents validate this matches the world they were designed for.
    pub schema_id: String,
    /// The full state as a JSON value — structure is world-defined.
    pub data: Value,
}

// ── WorldAction ───────────────────────────────────────────────────────────────

/// An action the brain decided to take in response to a perception.
///
/// Delivered to the world adapter via [`WorldAdapter::execute`]. The adapter
/// translates `kind` and `payload` into world-specific commands.
///
/// [`WorldAdapter::execute`]: crate::WorldAdapter::execute
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorldAction {
    /// World-defined action kind (e.g. `"move"`, `"speak"`, `"harvest"`, `"plan"`).
    pub kind: String,
    /// Action-specific parameters. Schema is world-defined.
    pub payload: Value,
    /// When the brain decided on this action.
    pub decided_at: DateTime<Utc>,
    /// Which brain pathway produced this action — for experiment tracking.
    pub pathway: BrainPathway,
}

impl WorldAction {
    /// Convenience constructor for simple actions with no payload.
    pub fn bare(kind: impl Into<String>, pathway: BrainPathway) -> Self {
        Self {
            kind: kind.into(),
            payload: Value::Null,
            decided_at: Utc::now(),
            pathway,
        }
    }

    /// Convenience constructor with a JSON payload.
    pub fn with_payload(kind: impl Into<String>, payload: Value, pathway: BrainPathway) -> Self {
        Self {
            kind: kind.into(),
            payload,
            decided_at: Utc::now(),
            pathway,
        }
    }
}

// ── ActionResult ──────────────────────────────────────────────────────────────

/// Feedback the world adapter returns after executing a [`WorldAction`].
///
/// Adapters may include this feedback in the next perception's events so the
/// agent can observe whether its actions had the intended effect.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActionResult {
    pub success: bool,
    /// Human-readable outcome for the agent's awareness.
    pub feedback: Option<String>,
    /// Whether executing this action changed the world state.
    pub state_changed: bool,
}

// ── WorldError ────────────────────────────────────────────────────────────────

/// Errors the world adapter may surface when executing agent actions.
#[derive(Debug, Error)]
pub enum WorldError {
    #[error("action '{kind}' rejected: {reason}")]
    ActionRejected { kind: String, reason: String },
    #[error("world adapter error: {detail}")]
    Adapter { detail: String },
    #[error("world not connected")]
    NotConnected,
    #[error("action timed out after {elapsed_ms}ms")]
    Timeout { elapsed_ms: u64 },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn perception_round_trip_json() {
        let perception = Perception {
            when: Utc::now(),
            sequence: 42,
            urgency: Urgency::High,
            signals: vec![
                Signal {
                    name: "cpu_usage".into(),
                    value: SignalValue::Float(0.85),
                    changed: true,
                    trend: Some(Trend::Rising),
                    urgency: Urgency::High,
                },
                Signal {
                    name: "is_active".into(),
                    value: SignalValue::Bool(true),
                    changed: false,
                    trend: None,
                    urgency: Urgency::Background,
                },
            ],
            events: vec![WorldEvent {
                kind: "alert".into(),
                source: Some("monitor".into()),
                payload: serde_json::json!({ "threshold": 0.8 }),
                urgency: Urgency::High,
            }],
            state: WorldState {
                schema_id: "cluster_v1".into(),
                data: serde_json::json!({ "nodes": 3 }),
            },
        };

        let json = serde_json::to_string(&perception).expect("serialization succeeds");
        let decoded: Perception = serde_json::from_str(&json).expect("deserialization succeeds");

        assert_eq!(decoded.sequence, 42);
        assert_eq!(decoded.urgency, Urgency::High);
        assert_eq!(decoded.signals.len(), 2);
        assert_eq!(decoded.signals[0].as_float(), Some(0.85));
        assert_eq!(decoded.signals[1].as_bool(), Some(true));
        assert_eq!(decoded.events.len(), 1);
        assert_eq!(decoded.state.schema_id, "cluster_v1");
    }

    #[test]
    fn world_action_round_trip_json() {
        let action = WorldAction::with_payload(
            "scale_replicas",
            serde_json::json!({ "replicas": 5 }),
            BrainPathway::Reflexive {
                model: "local-fast".into(),
            },
        );

        let json = serde_json::to_string(&action).expect("serialize action");
        let decoded: WorldAction = serde_json::from_str(&json).expect("deserialize action");

        assert_eq!(decoded.kind, "scale_replicas");
        assert_eq!(decoded.payload["replicas"], 5);
        match decoded.pathway {
            BrainPathway::Reflexive { model } => assert_eq!(model, "local-fast"),
            _ => panic!("unexpected pathway"),
        }
    }
}
